---
swagger: "2.0"
info:
  description: "User Service"
  version: "1.0.0"
  title: "用户服务"
  termsOfService: "https://github.com/Penetration-Platform-Go"
  contact:
    email: "chris-ju@qq.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "user"
  description: "Operations about user"
schemes:
- "http"
paths:
  /api/user/:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "Successful/Error"
    put:
      tags:
      - "user"
      summary: "Update user"
      operationId: "updateUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Update user object"
        required: true
        schema:
          $ref: "#/definitions/User"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "Successful/Error"
definitions:
  User:
    type: "object"
    properties:
      username:
        type: "string"
      nickname:
        type: "string"
      password:
        type: "string"
      email:
        type: "string"
      photo:
        type: "string"
